package com.ddsociety.projet_cinema.repositories;

import com.ddsociety.projet_cinema.entities.Film;
import com.ddsociety.projet_cinema.entities.projections.ListFilmProjection;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.List;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@RepositoryRestResource(excerptProjection = ListFilmProjection.class)
public interface FilmRepository extends CrudRepository<Film, Integer> {
    List<Film> findByCategorie_CodeCat(@Param("categorie") String categorie);
}
