package com.ddsociety.projet_cinema.repositories;

import com.ddsociety.projet_cinema.entities.Personnage;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@RepositoryRestResource
public interface PersonnageRepository extends CrudRepository<Personnage, Integer> {
    Page<Personnage> findByFilm_NoFilm(@Param("film") Integer film, Pageable pageable);
}
