package com.ddsociety.projet_cinema.repositories;

import com.ddsociety.projet_cinema.entities.Realisateur;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@Repository
public interface RealisateurRepository extends JpaRepository<Realisateur, Integer> {

}
