package com.ddsociety.projet_cinema.managers;

import com.ddsociety.projet_cinema.repositories.ActeurRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@Component
public class ActeurManager {

	@Autowired
	public ActeurManager(ActeurRepository acteurRepository) {
		this.acteurRepository = acteurRepository;
	}

	private ActeurRepository acteurRepository;

}
