package com.ddsociety.projet_cinema.managers;

import com.ddsociety.projet_cinema.repositories.CategorieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@Component
public class CategorieManager {

	@Autowired
	public CategorieManager(CategorieRepository categorieRepository) {
		this.categorieRepository = categorieRepository;
	}

	private CategorieRepository categorieRepository;

}
