package com.ddsociety.projet_cinema.managers;

import com.ddsociety.projet_cinema.repositories.FilmRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 12/10/2017
*/
@Component
public class FilmManager {

	@Autowired
	public FilmManager(FilmRepository filmRepository) {
		this.filmRepository = filmRepository;
	}

	private FilmRepository filmRepository;

}
